### PR TITLE
Nets Easy updates

### PR DESCRIPTION
**Pull request by bjarnef**
A few updates to Nets Easy documentation including some screenshots.

### CODE REVIEW

**Comment by bjarnef** [comment]
@mattbrailsford the documentation is updated now, and we can add further adjustments later.
I get some Vale error regarding the wording.

Part of it is probably fixes in https://github.com/vendrhub/vendr-documentation/pull/74 where I noticed some typos.

**Comment by bjarnef** [comment]
I have fixes the Vale errors regarding Nets Easy documentation, however it seems there are still a few which need to be fixed: https://github.com/vendrhub/vendr-documentation/pull/77/checks?check_run_id=2993595969

I think most of these has already been fixed in https://github.com/vendrhub/vendr-documentation/pull/74

**Comment by mattbrailsford** [comment]
I'll review the Vale errors later. I can't accept #74 though as reference docs are generated from source code so I need to update the source accordingly. I'll take a look at that later, but for now, these docs look good 👍

**Comment by bjarnef** [comment]
Ahh okay, I thought it was static markdown files as well. I will close PR https://github.com/vendrhub/vendr-documentation/pull/74 then, but feel free to look at the changes next time you are looking at the reference docs 📝

**Pull request merged**
